### ISSUE TITLE
Repo name too long, shorter name needed

### ISSUE THREAD

**Issue by conrad-heimbold** [conrad-heimbold/android-icon-pack-metadata-helper#2]
@beli3ver 

Hast du ne Idee für einen besseren Namen für mein Repo? Der derzeitige Name ist zu lang; es dürfte aber schwierig werden die ganzen Infos in einem kürzeren Namen unterzubringen... 

Der Name soll aussagen: 
- dass es um **Metadaten** (Paket-Name, Haupt-Akrivitäten, Icons)
- von **Android**-Apps
- auf **F-Droid** geht, die 
- explizit für **Icon Packs** gesammelt werden. 

Fällt dir noch ein Name ein?

**Comment by ghost** [comment]
FDroid Metas for Icon Packs
